# Generated by Django 4.2.4 on 2023-08-02 04:27

from django.db import migrations


def add_google_as_social_application(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    Site = apps.get_model("sites", "Site")
    google_app = SocialApp.objects.create(
        provider="google",
        name="Oauth-app",
        client_id="407151828957-0uans5irgrjpui7diuqpmkg1sct4okar.apps.googleusercontent.com",
        secret="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",
    )
    localhost_site = Site.objects.get(domain="example.com")
    google_app.sites.add(localhost_site)
    google_app.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_google_as_social_application),
    ]
